### ISSUE TITLE
UI is forgetting the admin api key on reboot

### ISSUE THREAD

**Issue by GamingDaveUk** [theroyallab/tabbyAPI-gradio-loader#1]
As topic title.
Created a bat file to load it, but that shouldnt* be the issue:
```
call venv\Scripts\activate
python webui.py
pause
```

Of course with these things, "shouldnt" is not always the same as "is not" lol

**Comment by DocShotgun** [comment]
Why would it be able to remember the admin key on reboot? It's only stored in runtime variables and not written to a file anywhere so there's no way for it to persist between sessions.

You can launch it with a bash script or a batch file that passes the IP and admin key with auto login:

```bash
#!/bin/bash
cd "$(dirname "$0")"
source ./venv/bin/activate
python webui.py -e http://0.0.0.0:5000 -k <admin_key>
```

**Comment by GamingDaveUk** [comment]
Will add it to the bash script. Have you thought about pulling the admin key in the same way as Tabby does setx TABBYADMIN_KEY "(admin key)"?
